{
 "title": "HMI",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Fluctuación de Resistencia Interna del MOSFET cuando esta encendido",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"binning_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"clasificacion_mosfet\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rds_on\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Rendimiento de Producción (Yield)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"binning_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"clasificacion_mosfet\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rds_on\") \r\n  |> group(columns: [\"categoria\"])\r\n  |> count()\r\n  |> yield(name: \"conteo\")"
    }
   ]
  },
  {
   "title": "Velocidad de Producción",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "uph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"binning_data\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"clasificacion_mosfet\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rds_on\")\r\n  |> count()\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * 4.0 })) \r\n  |> yield(name: \"uph_estimado\")"
    }
   ]
  }
 ]
}